import { useState } from 'react'
import { FileText, Download, Plus, Clock } from 'lucide-react'
import Header from '../components/Header'
import { MOCK_TEAMS } from '../data/mockData'

const SAMPLE_REPORTS = [
  { id: 1, title: 'UBC Thunder — Pre-Match Scout', team: 'UBC Thunder', type: 'Scouting', date: '2026-02-09', status: 'ready' },
  { id: 2, title: 'SFU Esports — Season Review W1-W4', team: 'SFU Esports', type: 'Performance', date: '2026-02-01', status: 'ready' },
  { id: 3, title: 'UVic Vikes — Post-Match Analysis', team: 'UVic Vikes', type: 'Analysis', date: '2026-02-17', status: 'ready' },
]

export default function Reports() {
  const [generating, setGenerating] = useState(false)
  const [selectedTeam, setSelectedTeam] = useState(MOCK_TEAMS[1].id)
  const [reportType, setReportType] = useState('scouting')
  const [reports, setReports] = useState(SAMPLE_REPORTS)

  function handleGenerate() {
    setGenerating(true)
    const team = MOCK_TEAMS.find(t => t.id === selectedTeam)
    setTimeout(() => {
      setReports(prev => [{
        id: Date.now(),
        title: `${team.name} — ${reportType === 'scouting' ? 'Pre-Match Scout' : reportType === 'performance' ? 'Performance Review' : 'Full Analysis'}`,
        team: team.name,
        type: reportType === 'scouting' ? 'Scouting' : reportType === 'performance' ? 'Performance' : 'Analysis',
        date: new Date().toISOString().split('T')[0],
        status: 'ready'
      }, ...prev])
      setGenerating(false)
    }, 1800)
  }

  function handleDownload(report) {
    const content = `VCT SCOUT — ${report.title.toUpperCase()}
${'='.repeat(50)}
Team: ${report.team}
Type: ${report.type} Report
Date: ${report.date}
Generated by: Valorant Collegiate Tool (VCT Scout)

This report contains scouting intelligence, player profiles,
map pool analysis, and strategic recommendations.

[Full report data would be populated from live match data
 when connected to the Riot Tournament API]

---
Powered by VCT Scout | vct-scout.vercel.app
Riot Games API — Tournament Match Data
`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.txt`
    a.click()
  }

  return (
    <div className="fade-in">
      <Header title="Reports" subtitle="Generate and export scouting & performance reports" />
      <div className="p-6 space-y-6">

        {/* Generator */}
        <div className="card p-5">
          <h3 className="text-white font-display text-base mb-4 flex items-center gap-2">
            <Plus size={14} className="text-val-red" /> Generate New Report
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
            <div>
              <label className="section-label">Team</label>
              <select value={selectedTeam} onChange={e => setSelectedTeam(e.target.value)}
                className="w-full mt-1 bg-val-darker border border-val-border text-white text-sm px-3 py-2 rounded-md font-mono focus:outline-none focus:border-val-red">
                {MOCK_TEAMS.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </div>
            <div>
              <label className="section-label">Report Type</label>
              <select value={reportType} onChange={e => setReportType(e.target.value)}
                className="w-full mt-1 bg-val-darker border border-val-border text-white text-sm px-3 py-2 rounded-md font-mono focus:outline-none focus:border-val-red">
                <option value="scouting">Pre-Match Scouting</option>
                <option value="performance">Performance Review</option>
                <option value="analysis">Full Analysis</option>
              </select>
            </div>
            <div className="flex items-end">
              <button onClick={handleGenerate} disabled={generating} className="btn-primary w-full">
                {generating ? (
                  <span className="flex items-center justify-center gap-2">
                    <span className="w-3 h-3 border border-white/30 border-t-white rounded-full animate-spin" />
                    Generating...
                  </span>
                ) : 'Generate Report'}
              </button>
            </div>
          </div>
          <p className="text-val-muted text-xs font-mono">
            Reports are generated from all tracked match data for the selected team. Connect Riot Tournament API for live data.
          </p>
        </div>

        {/* Report list */}
        <div className="space-y-3">
          {reports.map(r => (
            <div key={r.id} className="card p-4 flex items-center justify-between gap-4 hover:border-val-red/40 transition-colors">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded-lg bg-val-red/15 border border-val-red/30 flex items-center justify-center flex-shrink-0">
                  <FileText size={16} className="text-val-red" />
                </div>
                <div>
                  <div className="text-white font-display font-semibold text-sm">{r.title}</div>
                  <div className="flex items-center gap-3 mt-0.5">
                    <span className={`tag text-[9px] ${
                      r.type === 'Scouting' ? 'tag-red' : r.type === 'Performance' ? 'tag-teal' : 'tag-gold'
                    }`}>{r.type}</span>
                    <span className="text-val-muted text-xs font-mono flex items-center gap-1">
                      <Clock size={10} /> {r.date}
                    </span>
                  </div>
                </div>
              </div>
              <button
                onClick={() => handleDownload(r)}
                className="btn-ghost flex items-center gap-2 text-xs py-1.5"
              >
                <Download size={12} /> Export
              </button>
            </div>
          ))}
        </div>

        {/* Riot API callout */}
        <div className="border border-val-border rounded-lg p-5 bg-val-card">
          <h3 className="text-white font-display text-base mb-2">Unlock Full Reports with Riot API</h3>
          <p className="text-val-muted text-sm mb-3">
            With approved Riot Tournament API access, reports will include: full kill timelines, ability usage breakdowns, economy analysis per round, and agent-specific heatmaps.
          </p>
          <div className="flex flex-wrap gap-2">
            <span className="tag tag-muted">val/match/v1 — Match data</span>
            <span className="tag tag-muted">val/match/v1/timelines — Kill events</span>
            <span className="tag tag-muted">val/ranked/v1 — Rank verification</span>
          </div>
          <a
            href="https://developer.riotgames.com"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block mt-4 text-val-red text-xs font-mono hover:underline"
          >
            Apply for Riot API Access →
          </a>
        </div>
      </div>
    </div>
  )
}
